### ISSUE TITLE
apim cli behind a proxy

### ISSUE THREAD

**Issue by sbui-axway** [Axway-API-Management-Plus/apim-cli#109]
**API-Manager CLI Version**

1.2.2
**API-Manager and Service-Pack Version**
7.7 30072020

**Question**
How to use apim cli behind a proxy ?

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
Hi @sbui-axway, I haven't tested proxy support so far, but have you tried to set it using JVM-Options:
https://stackoverflow.com/questions/120797/how-do-i-set-the-proxy-to-be-used-by-the-jvm

You add these options in the apim.bat / apim.sh. It would be great if you can provide feedback if it is working or not.

**Comment by sbui-axway** [comment]
hi @cwiechmann , i try it with %_java% -Xms64m -Xmx256m -Dlog4j.configuration=../lib/log4j.xml -Dhttp.proxyHost=pxy-http-srv.serv.cdc.fr -Dhttp.proxyPort=8080 in the apim.bat, but it doesn't work.

Sébastien

**Comment by cwiechmann** [comment]
Hi @sbui-axway, I did some quick research and the reason, why the standard JVM-Proxy parameters are not working, is because the APIM-CLI is using internally the HTTP-Client from Apache, which has it's own way to support a proxy connection.

I have now added proxy support, but unfortunately I cannot test it easily, as I have no proxy available. So, could you please test if it is working as expected?

To use a proxy use the following parameters:
`-httpProxyHost proxy.host -httpProxyPort 7878 -httpProxyUsername myProxyUser -httpProxyPassword myProxyPW`

The intend is of course not to provide the proxy with every execution, instead configure that parameters with your stage (e.g. `conf/env.prod.properties`) or just global in `conf/env.properties`. Example:
```
httpProxyHost=proxyHost
httpProxyPort=8987
httpProxyUsername=proxyUser
httpProxyPassword=proxyPassword
```

[axway-apimcli-1.3.1-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/5588350/axway-apimcli-1.3.1-SNAPSHOT.zip)

Let me know, when it works (or not), so that I can complete this issue.

**Comment by jypdorongon** [comment]
@cwiechmann ,

The proxy update works perfectly. 

Thank you. 👍

**Comment by sbui-axway** [comment]
Hello @cwiechmann ,

i confirm, it work perfectly.

Thanks a lot.

Sébastien

**Comment by gwandwingor** [comment]
Hi @cwiechmann 
Do you plan on releasing 1.3.1 after this issue is merged or do on waiting for other potential issues a little longer ?

**Comment by cwiechmann** [comment]
I will release 1.3.1 today.
