### ISSUE TITLE
Modify API with HTTP Basic Outbound without affect password

### ISSUE THREAD

**Issue by giancolli** [Axway-API-Management-Plus/apim-cli#147]
**API-Manager CLI Version**
apim cli v 1.3.5

**API-Manager and Service-Pack Version**
7.7 - July

**Premise**
When an API with HTTP-Basic as Outbound is exported password is not saved, as normal. 
So, when I want to modify the API and then re-import it usually I add "password" field manually to api-config.json

**Question**
I want to ask if is possible to directly modify something in an API with HTTP Basic Outbound without need to: export-> add password & do modifications -> re-import.  So that I don't have to manually add "password" field.

In specific case, I need to modify Inbound auth in the API without effect HTTP Outbound password.

**Comment by cwiechmann** [comment]
Hi @giancolli, currently it's not supported what you are looking for. Of course, we could add this to the `api change` command, but in general that use case needs a better approach otherwise we end up with to many different change combinations. Perhaps `api change security` which would show the current security settings in an editor. However, this requires a lot of work and there is currently not enough bandwidth.

Concerning the missing password. 
Are you ware about this toggle?: 
`<VMArg name="-Dcom.axway.apimanager.api.model.disable.confidential.fields=true"/>`

See here for more information:
https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_relnotes/20200130_apimgr_relnotes/index.html

With that, the password would be exposed again and part of the API-Export.

**Comment by giancolli** [comment]
Hello @cwiechmann, thank you for pointing out the toggle, I will try with it!

Regarding what you said about `api change` command (that at the moment act on BE change) I tested it and seems that it does not maintain password in case of an API with HTTP Basic Outbound. Maybe I misunderstood something in your explanation.

I will keep you up to date, thank you for your effort.

**Comment by cwiechmann** [comment]
No, also the `api change` command should handle the passwords as the toggle I explained it valid for all passwords. If you need further help, please let me know.
