### ISSUE TITLE
Add field to organization

### ISSUE THREAD

**Issue by tcheronneau** [Axway-API-Management-Plus/apim-cli#203]
**User story**
We use some specific field that we add to organizations we deploy inside the APIM. 
When using directly the API you can add whatever field you want to the organization and it will works. 
When using the apim-cli it does not seems to be working (but no error). 

**Additional context**
Example file 
```
{
    "name": <orgname>,
    "description": "testing",
    "email": "<email>",
    "group_identifier_dn": "<dn>",
    "image": null,
    "restricted": false,
    "virtualHost": null,
    "phone": null,
    "enabled": true,
    "development": false,
    "startTrialDate": null,
    "endTrialDate": null,
    "trialDuration": null,
    "isTrial": null
}
```

I don't really see why it's not working with apim-cli I guess you're simply using the API.

**Comment by cwiechmann** [comment]
This is already supported by custom properties. However, in order to harmonize the behavior of custom properties for all entities, also the organization expects custom properties configured like so:
```json
{
  "name" : "Org with custom props",
  "description" : "Org with custom props",
  "enabled" : true,
  "development" : true,
  "customProperties": {
  	"mycustomproperty": "Org custom value 1"
  }
}
```

This is converted by the APIM-CLI into a request to the API-Manager as you expect:
```json
{
  "name": "Org with custom props",
  "description": "Org with custom props",
  "restricted": false,
  "enabled": true,
  "development": true,
  "mycustomproperty": "Org custom value 1"
}
```

But, you have to configure the possible custom properties upfront, as the APIM-CLI is validating this.
