### ISSUE TITLE
Enable Debug

### ISSUE THREAD

**Issue by pgcastro** [Axway-API-Management-Plus/apim-cli#215]
**API-Manager CLI Version**
1.3.7

**API-Manager and Service-Pack Version**
7.7

**Question**
I'm using APIM to import APIs and it is recreating the API all the time (even though API is existent as Published).
So, to understand a bit more, I wanted to enable debug logs (as per https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.1.-Enable-Debug) but for some reason I still don't see the debug logs. Am I missing something?

**Comment by cwiechmann** [comment]
Hi @pgcastro, 

There was an issue in the delivered log4j.xml, which was causing the Logging/Debugging not to work as expected. This has been fixed in version 1.3.11. 
So, my recommendation would be to upgrade the CLI and then it will work. 

Or check the log4j.xml here and compare it with your local version:
https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/modules/apim-adapter/src/main/resources/log4j.xml
