### ISSUE TITLE
Variable in API-config file gets not substituted anymore

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#257]
**API-Mgr. CLI version**
1.7.1

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
As stated in the documentation, variables in API-config files gets substituted by system environment variables
https://github.com/Axway-API-Management-Plus/apim-cli/wiki/2.1.2-API-Configuration-file#using-variables-in-api-config-file

**Actual behavior**
With version 1.7.x variables in API-config file gets not substituted anymore.

**Log-Output in Debug**

**Test case sample**
e.g. set in API-config file an outbound authentication profile. TEST_APIM_SECRET is set as system environment variable.
{
   "authenticationProfiles":[
      {
         "name":"_default",
         "isDefault":"true",
         "parameters":{
            "apiKey":"${TEST_APIM_SECRET}",
            "apiKeyField":"KeyId",
            "httpLocation":"HEADER"
         },
         "type":"apiKey"
      }
   ]
}
After running the CLI with version 1.6.1 apiKey was successfully set. But not with version 1.7.x

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @jschaefer77. 

Too bad, there was even a unit-test for this functionality. Unfortunately the problem was not discovered, because the Unit-Test sets a Properties-Object, which re-presents a `env.properties` or `env.<stage>.properties` file. 

The code has not replaced the Environment-Variable, when these properties are missing/null. 
Of course, this dependency makes no sense at all.

Now Environment-Variables are replaced first and the Unit-Test no longer sets this properties object to replicate the problem.

Additionally, I added assertions for all actions to make sure, the Property-Files (`env.properties` and/or `env.<stage>.properties`) are handled correctly and fixed it where required.
