### ISSUE TITLE
Quota takeover improvement

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apim-cli#258]
Hi,

**User story**
When a new version of an API that has application quotas is imported (re-created from new BE API), the existing app quotas are updated to the new 'not yet active' API before the old API version is removed.

We saw this happening because we accidentally hit the API Manager rate limit during quota takeover phase, which prevented the rollback from happening and left the 'old' version of the API still active while quotas were already applied to the 'new' API.

But I believe that in the context of an API that has hundreds of quotas to be taken over, this means that for a few seconds, until apim-cli quota takeover is finished and the old API version is removed, there are no quotas anymore on the old API version.

Maybe a safer way perform the quota take over would be to duplicate the constaint on the new API instead of updating the api Id on the existing one. Then, when the old API is removed, all the quotas related the old API would then be automatically cleaned up by API Manager.

What do you think ?

**Additional context**
See log
[apim-cli.log](https://github.com/Axway-API-Management-Plus/apim-cli/files/7971042/apim-cli.log)

**Comment by cwiechmann** [comment]
Thanks for sharing this use-case/requirement @gwandwingor and I even think, your apporach would be easier to implement. 

The downside of this approach is, that you are losing the current runtime quota usage. Every application would start with request number 1 of their configured quota.
The reason is, that you are creating new Quotas-Restrictions each with a new Restriction-ID. But the Restriction-Id is used in the quota runtime memory to maintain the current usage.

BTW: The error you see in the Log-File is caused by the rate-limit of the API-Manager (REST-API), which has been introduced some time ago:
https://support.axway.com/kb/181717/language/en
Perhaps, you should increase the threshold to avoid this error.

**Comment by gwandwingor** [comment]
Well, I indeed thought you had implemented it this way in order to keep current quota values. so I did a simple test on a local environment and found out that even with the current implementation, app quota takeover implies a reset of the current quota.
That's why I suggested this approach, but there may be some subtleties that I missed. I'll do more tests.

About the API Manager Rate limiting, thanks for pointing it out, we were aware of it but thought we'd never hit it, which was sadly proven wrong...

**Comment by cwiechmann** [comment]
@gwandwingor, Do you have any information based on the tests you made, that you can share already? Quota drives me crazy and perhaps it needs a again a massive refactoring.

**Comment by gwandwingor** [comment]
Hi,
Unfortunately, I didn't manage to find the time to test it further. The test I did was with the API and an App in different organizations. I wanted to try if the behaviour was different if API/App were in the same or different org.
I'll block some time next week to get to the bottom of this and get back to you in case I find something interesting.

**Comment by cwiechmann** [comment]
Thanks! @gwandwingor
