### ISSUE TITLE
How to mitigate changes in handling backendBasepath introduced with 468533e?

### ISSUE THREAD

**Issue by dynobo** [Axway-API-Management-Plus/apim-cli#341]
### APIM-CLI version

1.13.2

### Question

Dear apim-cli Team,

The change in 468533ea6668606fd39f909dbda563bd9c7f45b1 introduced an issue, which blocks us from upgrade to apim-cli `1.12.3+`.

We used to set our `backendBasepath` to `https://ourserver.com/api/v3`. Our methods paths defined in the imported openapi-specification start right after that basepath, so e.g. `/mymethod` for the method reachable under `https://ourserver.com/api/v3/mymethod`

With apim-cli `1.12.0` this was working well, it ended up in axway as:
- Backend API - Base URL: `https://ourserver.com`
- Backend API - Resource Path: `/api/v3/`
- Frontend API - Outbound -  Backend service URL: `https://ourserver.com/api/v3` <- :heavy_check_mark: 

With apim-cli `1.13.2` this leads to duplicated suffix in axway:
- Backend API - Base URL: `https://ourserver.com`
- Backend API - Resource Path: `/api/v3/`
- Frontend API - Outbound -  Backend service URL: `https://ourserver.com/api/v3/api/v3` <- :warning: 

As I understood from #299 and #307, the path should be stripped from the basepath now, so I tried setting `backendBasepath` to `https://ourserver.com`. But this ends up in axway as:
- Backend API - Base URL: `https://ourserver.com`
- Backend API - Resource Path: `/` <- :warning: 
- Frontend API - Outbound -  Backend service URL: `https://ourserver.com/` <- :warning: 

So the outbound URL now points to the wrong path, most likely because Resource Path in the Backend API is not correctly set anymore.

**Questions:**
1. If I'm _not_ supposed to add the path to `backendBasepath`, how can "Backend API - Resource Path" now be configured via `apim-cli`?
2. If I'm supposed to still _add_ the path to `backendBasepath`, how can I avoid the path duplication in the "Backend service URL"?

Thanks and best regards

**Comment by rathnapandi** [comment]
Hi @dynobo, 
Your observations are right. 
If I'm not supposed to add the path to backendBasepath, how can "Backend API - Resource Path" now be configured via apim-cli?
>> yes, the path will be used from API specification. 
If I'm supposed to still add the path to backendBasepath, how can I avoid the path duplication in the "Backend service URL"?
>> use **path** element in api config file . 
```
"name" : "petstore3",
  "path" : "/petstore",
```
Thanks

**Comment by rathnapandi** [comment]
Hi @dynobo, 

We need to use the URL.  I have tested with   openapi spec version 3.0.2. 

```
 "servers": [
    {
      "url": "/api/v3"
    }
  ],
```
or 

```
 "servers": [
    {
      "url": "https://api.acme.com/api/v3"
    }
  ],
```

Thanks
Rathna

**Comment by jschutte27** [comment]
We are trying to upgrade our pipelines from 1.12.3 to 1.13.2 and have had some pathing issues as well.  It appears that swagger 2 apis now need the path removed from backend basepath and openid 3 apis need the path added to backend basepath. 

Here is a debug log

[debuglog.txt](https://github.com/Axway-API-Management-Plus/apim-cli/files/10513148/debuglog.txt)

`{
	"name": "Test Deploy Warranty",
	"path": "/warranty-test-deploy",
	"state": "published",
	"version": "v2",
	"organization": "IT Developers",
	"backendBasepath": "${backend_basepath}",
	"securityProfiles": [
		{
			"name": "_default",
			"isDefault": true,
			"devices": [
				{
					"name": "API Key",
					"type": "apiKey",
					"order": 1,
					"properties": {
						"apiKeyFieldName": "KeyId",
						"takeFrom": "HEADER",
						"removeCredentialsOnSuccess": "true"
					}
				}
			]
		}
	]
}`

**Comment by dynobo** [comment]
@rathnapandi, I it tried it as you described, with setting `"backendBasepath": "https://our.server.com"` in the api config and `"servers": [{"url": "/api/v3"}]` in the openapi spec, but it doesn't work. It ends up in Axway as:

-  Backend API - Base URL: `https://our.server.com`
-  Backend API - Resource Path: `/` <- :warning: (should be `/api/v2`)
-  Frontend API - Outbound - Backend service URL: `https://our.server.com/` <- :warning: (should be `https://our.server.com/api/v2/`)

**Comment by rathnapandi** [comment]
Hi @dynobo, 

Currently CLI overrides resource and basepath using the variable backendbasepath defined in api-conig.json.  that's why you are seeing the behavior. 

I have fixed the issue to use url from server section defined in openapi and handle  backendbasepath properly. 

Sample config file
`{
  "name" : "petstore3",
  "path" : "/api/v2"
}
`
Openapi Servers section
<img width="371" alt="image" src="https://user-images.githubusercontent.com/3596610/215608259-8b362842-b69f-4e61-be0c-bbd56ad63174.png">


API Created with following 

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/3596610/215607803-0e7fcdc5-970f-4b99-928e-a68e0413f80a.png">

<img width="972" alt="image" src="https://user-images.githubusercontent.com/3596610/215608680-3a58ab8a-e48f-4d88-b18c-ee284286812d.png">

**Comment by rathnapandi** [comment]
Hi @dynobo , 

Currently CLI overrides resource and basepath using the variable backendbasepath defined in api-conig.json.  that's why you are seeing the behavior. 

I have fixed the issue to use url from server section defined in openapi and handle  backendbasepath properly. 

Sample config file
`{
  "name" : "petstore3",
  "path" : "/api/v2"
}
`
Openapi Servers section
<img width="371" alt="image" src="https://user-images.githubusercontent.com/3596610/215608259-8b362842-b69f-4e61-be0c-bbd56ad63174.png">


API Created with following 

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/3596610/215607803-0e7fcdc5-970f-4b99-928e-a68e0413f80a.png">

<img width="972" alt="image" src="https://user-images.githubusercontent.com/3596610/215608680-3a58ab8a-e48f-4d88-b18c-ee284286812d.png">

**Comment by dynobo** [comment]
@rathnapandi, I can confirm, that the snapshot of 1.13.3 you provided solves this issue for us. :+1: 

We're then just going to wait for it's official release before switching from 1.12.2 to 1.13.3 in our cicds, but from my side you can close this issue.

Thanks a lot for looking into it again! :slightly_smiling_face:

**Comment by rathnapandi** [comment]
Hi @dynobo, 
Thanks for validating and confirming.

**Comment by jschutte27** [comment]
Hi @rathnapandi, Thanks for looking at this.  Any plans for when 1.13.3 will be released?

**Comment by rathnapandi** [comment]
Hi @jschutte27, planning to release it before the end of next week.

**Comment by piglab** [comment]
Hi,
I just upgraded to 1.13.3, and this fix actually breaks the API imports.
I use the argument BackendBasepath to set the path of the backend API.
Does it mean thi argument is not used anymore ? And the value is always the one in the swaggerfile ?

thanks,

Olivier

**Comment by piglab** [comment]
I create an issue, not sure this thread is followed anymore : https://github.com/Axway-API-Management-Plus/apim-cli/issues/354
