### ISSUE TITLE
APIM CLI to check/skip already removed API

### ISSUE THREAD

**Issue by razvan4axway** [Axway-API-Management-Plus/apim-cli#417]
### Problem description

Issue:

Customer has a policy with API Manager that is event based and is called when an API is requested to be published.

They have automated the process.

As admin publishing is directly permitted, however as an Org admin this is forbidden. (No option in GUI)

Policy is doing the following: running validation and performing in place upgrade. 
1) reads the API to be published 
2) does validation 
3) Checks if API is in use
4) If predecessor is in place, it will publish the new API, will grant access to it and publish it. 
5) when #4 is correctly finish it will unpublish the old API and delete it
5b) If predecessor is unpublished, it will also delete it

Test case #1
Import unpublished API vs Currently published API - OK
When publishing the new API, the old is removed automatically

Test case #2
Import published API with changed path (breaking change) vs Unpublished API - KO

a)New API is created and published correctly
b)Unpublished API IS removed by the automation policy
c)APIM CLI tries to remove the previous API but as it is already deleted , it throws a 403 Response
d)APIM CLI next tries to rollback the new API but doesn't succeed to remove a published API because of the Org admin privileges(which is good)
This process raises some alarms on the client side

### Feature request

Possible solutions:
1) Implement a parameter/flag that skips deletion of old API
2) Check if API is still present and skip deletion if not present

**Comment by rathnapandi** [comment]
Hi @razvan4axway 
Instead of having a custom validation policy, can we do the following?
1. get api details using command./apim.sh api get -n "petstore" -o json which will get the api and its dependency like associated organizations and applications as json file. 
2. Enforce required validation (validate state, check for consumer etc...)
3.  Based on validation status either import new api or skip. 

Thanks
Rathna

**Comment by raffaelsta** [comment]
Hi Rathna,

keep the custom validation please out of scope, they're not relevant as it's anyway something custom. Nevertheless for each publication request there is an in place upgrade performed automatically directly after publication request on API Manager side which is creating conflicts with the procedure on CLI side. In theory this can also happen without such an automation so we would expect the APIM CLI to have a proper error handling:

- in case an API proxy which has to be deleted is not existing anymore, proceed instead of rolling back the entire import. Anyway the objective of this step is already fulfilled, the proxy does not exist anymore (independent who has deleted it).
An alternative as mentioned by razvan we could imagine to have a general flag can control if an predecessor should be deleted (as this is happening by our in place upgrade).

**Comment by rathnapandi** [comment]
Hi @raffaelsta  / @razvan4axway, 

Can you share the command line parameters used to deploy API?

**Comment by rathnapandi** [comment]
Hi @raffaelsta / @razvan4axway,

The fix check for api availability before deleting  exiting API.  can you test with
[axway-apimcli-1.14.3-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apim-cli/files/12665848/axway-apimcli-1.14.3-SNAPSHOT.tar.gz)

**Comment by raffaelsta** [comment]
Hi @rathnapandi,

thank you for this fix. From my end it's handling now the above mentioned issue in a proper way. Just thinking if the log level shouldn't be info/warning instead of error in such a case.

Anyway thanks for handling it!

**Comment by rathnapandi** [comment]
Fixed as part of 1.14.3 release
