### ISSUE TITLE
Change state from pending to published

### ISSUE THREAD

**Issue by lacg** [Axway-API-Management-Plus/apim-cli#97]
**User story**

My client has an API on the Pending state (waiting for approval) and he would like to change its state to Published using the CLI tool.

Thank you!

**Additional context**

**Comment by cwiechmann** [comment]
I think making the `approve` command a single command for the `api` is not a good idea, as their are many similar commands, such reject, deprecate, grant access, revoke, etc.
That’s why I’m thinking to implement it into a manage command: 
`apim api manage -s my-stage -action approve <some-api-filters>`
It will support the same API-Filters, so that a user can select the APIs he would like to apply the action to.
This can then be extended later with other actions.

**Comment by lacg** [comment]
> I think making the `approve` command a single command for the `api` is not a good idea, as their are many similar commands, such reject, deprecate, grant access, revoke, etc.
> That’s why I’m thinking to implement it into a manage command:
> `apim api manage -s my-stage -action approve <some-api-filters>`
> It will support the same API-Filters, so that a user can select the APIs he would like to apply the action to.
> This can then be extended later with other actions.

Agreed!

**Comment by cwiechmann** [comment]
The new feature is implemented and will be delivered with the next version mid of November. 

FYI: I had a chat with a colleague and we concluded to add this new command along the others like so:
```
Available commands:
apim api import          Import APIs into the API-Manager
apim api delete          Delete the selected APIs from the API-Manager
apim api get             Get APIs from API-Manager in different formats
apim api change          Changes the selected APIs according to given parameters
apim api unpublish       Unpublish the selected APIs
apim api publish         Publish the selected APIs
apim api approve         Approves selected APIs that are in pending state
```
We think it doesn't harm to have maybe up to twenty commandos listed there. It's better instead of adding another virtual level with the `action` toggle. And the other reason was, that commands like publish, unpuplish are already there.

I'm closing this issue now. Thanks @lacg.
